container_image = docker://sncromp/geodes:3
universe = container

LR = 1e-5
Epochs = 20
ImageTag = 2d_snr5_3
ImageModel = /staging/cromp/6351466.tar.gz

RUNNAME = main_3d_3
executable = 3d.sh
arguments = $(RUNNAME) $(Cluster) $(LR) $(Epochs) $(ImageModel) $(ImageTag)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz
requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 1
require_gpus = (GlobalMemoryMB >= 90000)
+WantGPULab = true
+GPUJobLength = "medium"
request_cpus = 1
request_memory = 100GB
request_disk = 300GB
queue 1