container_image = docker://sncromp/geodes:3
universe = container

LR = 1e-5
Epochs = 20
#ImageTag = 2d_snr5_2
#ImageModel = /staging/cromp/6351465.tar.gz

RUNNAME = wm_3d
executable = 3d_wm.sh
arguments = $(RUNNAME) $(Cluster) $(LR) $(Epochs) $(ImageModel) $(ImageTag)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz
requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 2
require_gpus = (GlobalMemoryMB >= 48000)
+WantGPULab = true
+GPUJobLength = "medium"
request_cpus = 1
request_memory = 100GB
request_disk = 300GB
queue 1