container_image = docker://sncromp/geodes:3
universe = container 

Dataset = /staging/groups/cs_geodes/cyclone/multivar/date/natlantic.tar.gz
Channelfile = /staging/groups/cs_geodes/cyclone/multivar/date/channels.txt
Split = test
VideoModel = ablate_3d_mse_6293588.tar.gz

RUNNAME = samples_$(VideoModel)

executable = s_ablate.sh
arguments = $(RUNNAME) $(Cluster) $(Process) $(Dataset) $(Channelfile) $(Split) $(VideoModel)
output = logs/$(RUNNAME)_$(Cluster)_$(Process).out
log = logs/$(RUNNAME)_$(Cluster)_$(Process).log
error = logs/$(RUNNAME)_$(Cluster)_$(Process).err

should_transfer_files = YES
#transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz

requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 1
require_gpus = (GlobalMemoryMB >= 32000)

+WantGPULab = true
+GPUJobLength = "short"

request_cpus = 1
request_memory = 100GB
request_disk = 300GB

queue 15