container_image = docker://sncromp/geodes:3
universe = container

LR = 5e-7
Epochs = 25
ModelName = 3d_snr-5.5_6008211

RUNNAME = fft_mse.mse_snr_run1_6008211
executable = 3d_fft_snrmse.sh
arguments = $(RUNNAME) $(Cluster) $(LR) $(Epochs) $(ModelName)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz
requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 2
require_gpus = (GlobalMemoryMB >= 48000)
+WantGPULab = true
+GPUJobLength = "medium"
request_cpus = 2
request_memory = 100GB
request_disk = 300GB
queue 1