container_image = docker://sncromp/geodes:3
universe = container

LR = 5e-7
Epochs = 25
ModelName = main_3d_l1.h25_run3_6280745

RUNNAME = fft_l1.h25_run3_6280745
executable = 3d_fft.sh
arguments = $(RUNNAME) $(Cluster) $(LR) $(Epochs) $(ModelName)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz
requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 2
require_gpus = (GlobalMemoryMB >= 48000)
+WantGPULab = true
+GPUJobLength = "medium"
request_cpus = 2
request_memory = 100GB
request_disk = 300GB
queue 1