container_image = docker://sncromp/geodes:3
universe = container

LR = 5e-7
Epochs = 25
ModelName = main_3d_l1.h25_run3_6094414

RUNNAME = fft_l1.h25_snr_run3_6094414
executable = 3d_fft_snr.sh
arguments = $(RUNNAME) $(Cluster) $(LR) $(Epochs) $(ModelName)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz
requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 1
require_gpus = (GlobalMemoryMB >= 96000)
+WantGPULab = true
+GPUJobLength = "medium"
request_cpus = 1
request_memory = 100GB
request_disk = 300GB
queue 1