container_image = docker://sncromp/geodes:4
universe = container

inname = /staging/groups/cs_geodes/fft_l1.h25_run2_6280744_6330489_swa.tar.gz
outname = /staging/groups/cs_geodes/fft_l1.h25_run2_6280744_6330489_swaveaged.tar.gz

RUNNAME = merging_fft_l1.h25_run2_6280744_6330489_swa
executable = swa_merge.sh
arguments = $(RUNNAME) $(Cluster) $(inname) $(outname)

output = logs/$(RUNNAME).$(Cluster).out
log = logs/$(RUNNAME).$(Cluster).log
error = logs/$(RUNNAME).$(Cluster).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/scripts-geodes-chtc/fft/swa_merge.py
requirements = (Target.HasCHTCStaging == True)
request_cpus = 1
request_memory = 100GB
request_disk = 300GB
queue 1

