container_image = docker://sncromp/geodes:3
universe = container 

Dataset = /staging/groups/cs_geodes/cyclone/windmag/date/natlantic.tar.gz
Split = test
#VideoModel = windmag_svd_train_NUMBERHERE

RUNNAME = $(VideoModel)_sample_natlantic_$(Split)

executable = s_l1.h25.sh
arguments = $(RUNNAME) $(Cluster) $(Process) $(Dataset) $(Split) $(VideoModel)
output = logs/$(RUNNAME)_$(Cluster)_$(Process).out
log = logs/$(RUNNAME)_$(Cluster)_$(Process).log
error = logs/$(RUNNAME)_$(Cluster)_$(Process).err

should_transfer_files = YES
transfer_input_files = /home/cromp/geodes-project/geodes.tar.gz

requirements = (CUDACapability >= 4) && (Target.HasCHTCStaging == True)
request_gpus = 1
require_gpus = (GlobalMemoryMB >= 32000)

+WantGPULab = true
+GPUJobLength = "long"

request_cpus = 1
request_memory = 100GB
request_disk = 300GB

queue 1